@startuml
title クラス図

' メイン画面クラス
class MainWindow #LightCoral

' 各種機能クラス
abstract ProcessBase #LightGreen
class ProcessConfigBase #LightGreen
'class _OtherProcesses_ #LightGreen

class ProcessWatched #LightGreen
class ProcessNotWatched #LightGreen
class ProcessVideoPlay #LightGreen
class ProcessMoveUp #LightGreen
class ProcessMoveDown #LightGreen
class ProcessWatchedMylist #LightGreen
class ProcessWatchedAllMylist #LightGreen
class ProcessSearch #LightGreen
class ProcessShowMylistInfo #LightGreen
class ProcessCreateMylist #LightGreen
class ProcessCreateMylistThreadDone #LightGreen
class ProcessDeleteMylist #LightGreen
class ProcessUpdateMylistInfo #LightGreen
class ProcessUpdateMylistInfoThreadDone #LightGreen

class ProcessUpdateAllMylistInfo #LightGreen
class ProcessUpdateAllMylistInfoThreadProgress #LightGreen
class ProcessUpdateAllMylistInfoThreadDone #LightGreen

abstract ProcessConfigBase #LightGreen
class ProcessConfigSave #LightGreen
class ProcessMylistSaveCSV #LightGreen
class ProcessMylistLoadCSV #LightGreen

class Timer #LightGreen


' SQLalchemy関連クラス
abstract Base #LightBlue{
    SQLalchemy Base
}
class Mylist #LightBlue{
    Model
}
class MylistInfo #LightBlue{
    Model
}

' SQLalchemy関連
Base <|.. Mylist
Base <|.. MylistInfo

' 各種機能クラス関連
ProcessBase <|.. ProcessConfigBase

ProcessBase <|.. ProcessWatched
ProcessBase <|.. ProcessNotWatched
ProcessBase <|.. ProcessVideoPlay
ProcessBase <|... ProcessMoveUp
ProcessBase <|... ProcessMoveDown
ProcessBase <|... ProcessWatchedMylist
ProcessBase <|... ProcessWatchedAllMylist
ProcessBase <|... ProcessSearch
ProcessBase <|.. ProcessShowMylistInfo
ProcessBase <|.. ProcessCreateMylist
ProcessBase <|.. ProcessCreateMylistThreadDone
ProcessBase <|.. ProcessDeleteMylist
ProcessBase <|... ProcessUpdateMylistInfo
ProcessBase <|... ProcessUpdateMylistInfoThreadDone
ProcessBase <|... ProcessUpdateAllMylistInfoThreadProgress
ProcessBase <|... ProcessUpdateAllMylistInfoThreadDone

ProcessUpdateMylistInfo <|.. ProcessUpdateAllMylistInfo

ProcessConfigBase <|.. ProcessConfigSave
ProcessConfigBase <|.. ProcessMylistSaveCSV
ProcessConfigBase <|.. ProcessMylistLoadCSV

ProcessBase <|.. Timer

' メイン画面クラスはSQLalchemy基本を保持する(has a)
MainWindow o- Base

' メイン画面クラスは各種機能クラスを保持する(has a)
MainWindow o-- ProcessBase

@enduml